/**
 * Convert validated canonical topics into stable routes and search documents.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - function topicUrl: line 17
 * - function topicText: line 22
 * - function toTopicDocument: line 37
 * - function toSearchDocument: line 42
 * @@SYMBOL_INDEX_END
 */

import type { CollectionEntry } from "astro:content";
import type { SearchDocument, TopicDocument } from "./contracts";

/** Build the canonical, version-qualified route for one public topic. */
export function topicUrl(topic: TopicDocument): string {
  return `/docs/${encodeURIComponent(topic.productId)}/${encodeURIComponent(topic.version)}/${encodeURIComponent(topic.topicSlug)}/`;
}

/** Flatten sections into plain searchable text without injecting markup. */
export function topicText(topic: TopicDocument): string {
  return topic.sections
    .flatMap((section) => [
      ...section.paragraphs,
      ...(section.steps ?? []),
      section.code ?? "",
      section.warning?.condition ?? "",
      section.warning?.consequence ?? "",
      section.warning?.avoidance ?? "",
    ])
    .filter((value) => value.length > 0)
    .join(" ");
}

/** Map one schema-validated Astro entry into the repository's public contract. */
export function toTopicDocument(entry: CollectionEntry<"topics">): TopicDocument {
  return entry.data;
}

/** Map one topic into a compact, serializable search record. */
export function toSearchDocument(topic: TopicDocument): SearchDocument {
  return {
    id: topic.id,
    title: topic.title,
    summary: topic.summary,
    headings: topic.sections.map((section) => section.title),
    body: topicText(topic),
    identifiers: topic.identifiers,
    synonyms: topic.synonyms,
    productId: topic.productId,
    productName: topic.productName,
    version: topic.version,
    lifecycle: topic.lifecycle,
    url: topicUrl(topic),
  };
}
