/**
 * Define the stable product, topic, search, citation, and answer contracts.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - type Lifecycle: line 24
 * - type ContentType: line 25
 * - interface ProductVersion: line 27
 * - interface Product: line 34
 * - interface WarningNotice: line 41
 * - interface TopicSection: line 48
 * - interface TopicDocument: line 57
 * - interface SearchDocument: line 79
 * - interface Posting: line 94
 * - interface SearchIndex: line 99
 * - interface SearchFilters: line 106
 * - interface SearchOptions: line 111
 * - interface SearchResult: line 115
 * - interface Citation: line 121
 * - type GroundedAnswer: line 128
 * @@SYMBOL_INDEX_END
 */

export type Lifecycle = "current" | "maintained" | "retired";
export type ContentType = "concept" | "task" | "reference" | "troubleshooting";

export interface ProductVersion {
  readonly version: string;
  readonly lifecycle: Lifecycle;
  readonly released: string;
  readonly endOfSupport?: string;
}

export interface Product {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly versions: readonly ProductVersion[];
}

export interface WarningNotice {
  readonly level: "notice" | "caution" | "warning" | "danger";
  readonly condition: string;
  readonly consequence: string;
  readonly avoidance: string;
}

export interface TopicSection {
  readonly id: string;
  readonly title: string;
  readonly paragraphs: readonly string[];
  readonly steps?: readonly string[] | undefined;
  readonly code?: string | undefined;
  readonly warning?: WarningNotice | undefined;
}

export interface TopicDocument {
  readonly id: string;
  readonly topicSlug: string;
  readonly title: string;
  readonly summary: string;
  readonly productId: string;
  readonly productName: string;
  readonly version: string;
  readonly lifecycle: Lifecycle;
  readonly contentType: ContentType;
  readonly identifiers: readonly string[];
  readonly synonyms: readonly string[];
  readonly updated: string;
  readonly visibility: "public";
  readonly provenance: {
    readonly sourceId: string;
    readonly pages: readonly number[];
    readonly checksum: string;
  };
  readonly sections: readonly TopicSection[];
}

export interface SearchDocument {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly headings: readonly string[];
  readonly body: string;
  readonly identifiers: readonly string[];
  readonly synonyms: readonly string[];
  readonly productId: string;
  readonly productName: string;
  readonly version: string;
  readonly lifecycle: Lifecycle;
  readonly url: string;
}

export interface Posting {
  readonly documentIndex: number;
  readonly weightedFrequency: number;
}

export interface SearchIndex {
  readonly documents: readonly SearchDocument[];
  readonly postings: ReadonlyMap<string, readonly Posting[]>;
  readonly documentLengths: readonly number[];
  readonly averageDocumentLength: number;
}

export interface SearchFilters {
  readonly productId?: string;
  readonly version?: string;
}

export interface SearchOptions extends SearchFilters {
  readonly limit?: number;
}

export interface SearchResult {
  readonly document: SearchDocument;
  readonly score: number;
  readonly matchedTerms: readonly string[];
}

export interface Citation {
  readonly title: string;
  readonly url: string;
  readonly productName: string;
  readonly version: string;
}

export type GroundedAnswer =
  | {
      readonly status: "answered";
      readonly text: string;
      readonly citations: readonly Citation[];
    }
  | {
      readonly status: "abstained";
      readonly reason: string;
      readonly citations: readonly [];
    };
