/**
 * Resolve reviewed legacy paths without allowing open or external redirects.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable LEGACY_REDIRECTS: line 11
 * - function resolveLegacyRedirect: line 19
 * @@SYMBOL_INDEX_END
 */

export const LEGACY_REDIRECTS: Readonly<Record<string, string>> = Object.freeze({
  "/manuals/apex/latest/e104": "/docs/apex-control-hub/2.0/error-e-104/",
  "/manuals/apex/1.5/network-error": "/docs/apex-control-hub/1.5/error-e-104/",
  "/manuals/northstar/latest/calibration":
    "/docs/northstar-io-gateway/3.2/analog-input-calibration/",
});

/** Return only repository-local, predeclared redirect targets. */
export function resolveLegacyRedirect(pathname: string): string | undefined {
  const target = LEGACY_REDIRECTS[pathname];
  return target?.startsWith("/") && !target.startsWith("//") ? target : undefined;
}
