/**
 * Bind the accessible search form without inserting untrusted HTML into the DOM.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable INPUT_DELAY_MILLISECONDS: line 20
 * - variable SCORE_DECIMAL_PLACES: line 21
 * - type ElementConstructor: line 23
 * - function requireElement: line 26
 * - function textElement: line 39
 * - function renderResults: line 53
 * - function renderAnswer: line 85
 * - function initializeSearch: line 105
 * @@SYMBOL_INDEX_END
 */

import type { GroundedAnswer, SearchDocument, SearchResult } from "./contracts";
import { answerQuestion, createSearchIndex, search } from "./search";

const INPUT_DELAY_MILLISECONDS = 160;
const SCORE_DECIMAL_PLACES = 2;

type ElementConstructor<T extends HTMLElement> = new () => T;

/** Require an element with the expected browser interface. */
function requireElement<T extends HTMLElement>(
  root: ParentNode,
  selector: string,
  expected: ElementConstructor<T>,
): T {
  const element = root.querySelector(selector);
  if (!(element instanceof expected)) {
    throw new Error(`search component is missing ${selector}`);
  }
  return element;
}

/** Append plain text to one newly created element. */
function textElement<K extends keyof HTMLElementTagNameMap>(
  tagName: K,
  text: string,
  className?: string,
): HTMLElementTagNameMap[K] {
  const element = document.createElement(tagName);
  element.textContent = text;
  if (className !== undefined) {
    element.className = className;
  }
  return element;
}

/** Render ranked results using textContent so corpus text cannot become active HTML. */
function renderResults(container: HTMLElement, results: readonly SearchResult[]): void {
  container.replaceChildren();
  if (results.length === 0) {
    container.append(
      textElement("p", "No version-matched results. Try an identifier or broader term."),
    );
    return;
  }

  const list = document.createElement("ol");
  list.className = "search-results";
  for (const result of results) {
    const item = document.createElement("li");
    const link = document.createElement("a");
    link.href = result.document.url;
    link.textContent = result.document.title;
    item.append(
      link,
      textElement(
        "p",
        `${result.document.productName} ${result.document.version} · ${result.document.lifecycle}`,
        "result-meta",
      ),
      textElement("p", result.document.summary),
      textElement("span", `Relevance ${result.score.toFixed(SCORE_DECIMAL_PLACES)}`, "score"),
    );
    list.append(item);
  }
  container.append(list);
}

/** Render a cited extractive answer or the explicit abstention reason. */
function renderAnswer(container: HTMLElement, answer: GroundedAnswer): void {
  container.replaceChildren();
  if (answer.status === "abstained") {
    container.append(textElement("p", `Answer unavailable: ${answer.reason}`));
    return;
  }
  container.append(textElement("p", answer.text));
  const citations = document.createElement("ul");
  for (const citation of answer.citations) {
    const item = document.createElement("li");
    const link = document.createElement("a");
    link.href = citation.url;
    link.textContent = `${citation.title} — ${citation.productName} ${citation.version}`;
    item.append(link);
    citations.append(item);
  }
  container.append(citations);
}

/** Initialize one search panel and return a cleanup function for hot reloads/tests. */
export function initializeSearch(
  root: HTMLElement,
  documents: readonly SearchDocument[],
): () => void {
  const input = requireElement(root, "[data-search-input]", HTMLInputElement);
  const product = requireElement(root, "[data-product-filter]", HTMLSelectElement);
  const version = requireElement(root, "[data-version-filter]", HTMLSelectElement);
  const status = requireElement(root, "[data-search-status]", HTMLElement);
  const results = requireElement(root, "[data-search-results]", HTMLElement);
  const answer = requireElement(root, "[data-grounded-answer]", HTMLElement);
  const index = createSearchIndex(documents);
  let timer: number | undefined;

  const execute = (): void => {
    const query = input.value.trim();
    const filters = {
      ...(product.value === "" ? {} : { productId: product.value }),
      ...(version.value === "" ? {} : { version: version.value }),
    };
    const matches = query === "" ? [] : search(index, query, { ...filters, limit: 8 });
    renderResults(results, matches);
    renderAnswer(
      answer,
      query === ""
        ? { status: "abstained", reason: "Enter a question first.", citations: [] }
        : answerQuestion(index, query, filters),
    );
    status.textContent =
      query === ""
        ? "Enter a search term."
        : `${matches.length} ranked result${matches.length === 1 ? "" : "s"}.`;
  };

  const schedule = (): void => {
    if (timer !== undefined) {
      window.clearTimeout(timer);
    }
    timer = window.setTimeout(execute, INPUT_DELAY_MILLISECONDS);
  };

  input.addEventListener("input", schedule);
  product.addEventListener("change", execute);
  version.addEventListener("change", execute);
  execute();

  return () => {
    input.removeEventListener("input", schedule);
    product.removeEventListener("change", execute);
    version.removeEventListener("change", execute);
    if (timer !== undefined) {
      window.clearTimeout(timer);
    }
  };
}
