/**
 * Build and query a bounded lexical index with version filters and abstention.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable MAX_QUERY_CHARACTERS: line 45
 * - variable MAX_QUERY_TOKENS: line 46
 * - variable DEFAULT_RESULT_LIMIT: line 47
 * - variable MAX_RESULT_LIMIT: line 48
 * - variable TITLE_WEIGHT: line 49
 * - variable IDENTIFIER_WEIGHT: line 50
 * - variable SYNONYM_FIELD_WEIGHT: line 51
 * - variable PRODUCT_WEIGHT: line 52
 * - variable HEADING_WEIGHT: line 53
 * - variable SUMMARY_WEIGHT: line 54
 * - variable BODY_WEIGHT: line 55
 * - variable EXACT_IDENTIFIER_BOOST: line 56
 * - variable EXACT_TITLE_PHRASE_BOOST: line 57
 * - variable SYNONYM_WEIGHT: line 58
 * - variable BM25_K1: line 59
 * - variable BM25_B: line 60
 * - variable ANSWER_SCORE_THRESHOLD: line 61
 * - function tokenize: line 64
 * - function normalizeIdentifier: line 70
 * - function addField: line 75
 * - function createSearchIndex: line 84
 * - function queryTerms: line 116
 * - function matchesFilters: line 133
 * - function search: line 141
 * - function answerQuestion: line 231
 * @@SYMBOL_INDEX_END
 */

import { SYNONYMS } from "../data/synonyms";
import type {
  GroundedAnswer,
  Posting,
  SearchDocument,
  SearchFilters,
  SearchIndex,
  SearchOptions,
  SearchResult,
} from "./contracts";

const MAX_QUERY_CHARACTERS = 160;
const MAX_QUERY_TOKENS = 12;
const DEFAULT_RESULT_LIMIT = 8;
const MAX_RESULT_LIMIT = 20;
const TITLE_WEIGHT = 5;
const IDENTIFIER_WEIGHT = 8;
const SYNONYM_FIELD_WEIGHT = 4;
const PRODUCT_WEIGHT = 1.5;
const HEADING_WEIGHT = 3;
const SUMMARY_WEIGHT = 2;
const BODY_WEIGHT = 1;
const EXACT_IDENTIFIER_BOOST = 25;
const EXACT_TITLE_PHRASE_BOOST = 10;
const SYNONYM_WEIGHT = 0.65;
const BM25_K1 = 1.2;
const BM25_B = 0.75;
const ANSWER_SCORE_THRESHOLD = 3;

/** Normalize user-visible text without attempting locale-specific stemming. */
export function tokenize(value: string): readonly string[] {
  const normalized = value.normalize("NFKC").toLocaleLowerCase("en-US");
  return normalized.match(/[\p{L}\p{N}]+(?:[._-][\p{L}\p{N}]+)*/gu) ?? [];
}

/** Convert identifiers into the exact form used by the dedicated boost. */
function normalizeIdentifier(value: string): string {
  return value.normalize("NFKC").trim().toLocaleUpperCase("en-US");
}

/** Add weighted terms from one field to a document-local frequency table. */
function addField(frequencies: Map<string, number>, value: string, weight: number): number {
  const tokens = tokenize(value);
  for (const token of tokens) {
    frequencies.set(token, (frequencies.get(token) ?? 0) + weight);
  }
  return tokens.length;
}

/** Create an immutable inverted index in O(total document tokens) time. */
export function createSearchIndex(documents: readonly SearchDocument[]): SearchIndex {
  const mutablePostings = new Map<string, Posting[]>();
  const documentLengths: number[] = [];

  for (const [documentIndex, document] of documents.entries()) {
    const frequencies = new Map<string, number>();
    let length = addField(frequencies, document.title, TITLE_WEIGHT);
    length += addField(frequencies, document.summary, SUMMARY_WEIGHT);
    length += addField(frequencies, document.headings.join(" "), HEADING_WEIGHT);
    length += addField(frequencies, document.body, BODY_WEIGHT);
    length += addField(frequencies, document.identifiers.join(" "), IDENTIFIER_WEIGHT);
    length += addField(frequencies, document.synonyms.join(" "), SYNONYM_FIELD_WEIGHT);
    length += addField(frequencies, document.productName, PRODUCT_WEIGHT);
    documentLengths.push(Math.max(length, 1));

    for (const [term, weightedFrequency] of frequencies) {
      const postings = mutablePostings.get(term) ?? [];
      postings.push({ documentIndex, weightedFrequency });
      mutablePostings.set(term, postings);
    }
  }

  const totalLength = documentLengths.reduce((sum, length) => sum + length, 0);
  return {
    documents: [...documents],
    postings: mutablePostings,
    documentLengths,
    averageDocumentLength: documents.length === 0 ? 1 : totalLength / documents.length,
  };
}

/** Expand only the bounded reviewed synonym map; never recurse expansions. */
function queryTerms(query: string): ReadonlyMap<string, number> {
  const weightedTerms = new Map<string, number>();
  const baseTokens = tokenize(query.slice(0, MAX_QUERY_CHARACTERS)).slice(0, MAX_QUERY_TOKENS);
  for (const token of baseTokens) {
    weightedTerms.set(token, 1);
    for (const synonym of SYNONYMS[token] ?? []) {
      for (const expandedToken of tokenize(synonym)) {
        if (!weightedTerms.has(expandedToken)) {
          weightedTerms.set(expandedToken, SYNONYM_WEIGHT);
        }
      }
    }
  }
  return weightedTerms;
}

/** Check product/version filters before scoring a candidate. */
function matchesFilters(document: SearchDocument, filters: SearchFilters): boolean {
  return (
    (filters.productId === undefined || document.productId === filters.productId) &&
    (filters.version === undefined || document.version === filters.version)
  );
}

/** Query the inverted index in O(query postings + result sorting) time. */
export function search(
  index: SearchIndex,
  query: string,
  options: SearchOptions = {},
): readonly SearchResult[] {
  const terms = queryTerms(query);
  if (terms.size === 0 || index.documents.length === 0) {
    return [];
  }

  const scores = new Map<number, number>();
  const matches = new Map<number, Set<string>>();
  const documentCount = index.documents.length;

  for (const [term, queryWeight] of terms) {
    const postings = index.postings.get(term) ?? [];
    if (postings.length === 0) {
      continue;
    }
    const inverseDocumentFrequency = Math.log(
      1 + (documentCount - postings.length + 0.5) / (postings.length + 0.5),
    );
    for (const posting of postings) {
      const document = index.documents[posting.documentIndex];
      const documentLength = index.documentLengths[posting.documentIndex];
      if (
        document === undefined ||
        documentLength === undefined ||
        !matchesFilters(document, options)
      ) {
        continue;
      }
      const normalizedLength = 1 - BM25_B + BM25_B * (documentLength / index.averageDocumentLength);
      const termScore =
        inverseDocumentFrequency *
        ((posting.weightedFrequency * (BM25_K1 + 1)) /
          (posting.weightedFrequency + BM25_K1 * normalizedLength)) *
        queryWeight;
      scores.set(posting.documentIndex, (scores.get(posting.documentIndex) ?? 0) + termScore);
      const matched = matches.get(posting.documentIndex) ?? new Set<string>();
      matched.add(term);
      matches.set(posting.documentIndex, matched);
    }
  }

  const exactIdentifier = normalizeIdentifier(query);
  const normalizedQuery = query.trim().toLocaleLowerCase("en-US");
  for (const [documentIndex, currentScore] of scores) {
    const document = index.documents[documentIndex];
    if (document === undefined) {
      continue;
    }
    let boostedScore = currentScore;
    if (
      document.identifiers.some((identifier) => normalizeIdentifier(identifier) === exactIdentifier)
    ) {
      boostedScore += EXACT_IDENTIFIER_BOOST;
    }
    if (
      normalizedQuery.length > 2 &&
      document.title.toLocaleLowerCase("en-US").includes(normalizedQuery)
    ) {
      boostedScore += EXACT_TITLE_PHRASE_BOOST;
    }
    scores.set(documentIndex, boostedScore);
  }

  const requestedLimit = options.limit ?? DEFAULT_RESULT_LIMIT;
  const limit = Math.max(1, Math.min(requestedLimit, MAX_RESULT_LIMIT));
  return [...scores.entries()]
    .flatMap(([documentIndex, score]) => {
      const document = index.documents[documentIndex];
      return document === undefined
        ? []
        : [
            {
              document,
              score,
              matchedTerms: [...(matches.get(documentIndex) ?? [])].sort(),
            },
          ];
    })
    .sort(
      (left, right) =>
        right.score - left.score || left.document.id.localeCompare(right.document.id, "en-US"),
    )
    .slice(0, limit);
}

/** Produce an extractive answer with citations or explicitly abstain. */
export function answerQuestion(
  index: SearchIndex,
  question: string,
  filters: SearchFilters = {},
): GroundedAnswer {
  const results = search(index, question, { ...filters, limit: 2 });
  const leading = results[0];
  if (leading === undefined || leading.score < ANSWER_SCORE_THRESHOLD) {
    return {
      status: "abstained",
      reason: "No sufficiently relevant, version-matched source was found.",
      citations: [],
    };
  }

  return {
    status: "answered",
    text: leading.document.summary,
    citations: results.map(({ document }) => ({
      title: document.title,
      url: document.url,
      productName: document.productName,
      version: document.version,
    })),
  };
}
