/**
 * Configure deterministic static output, canonical URLs, and secure defaults.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - no top-level symbols
 * @@SYMBOL_INDEX_END
 */

import { defineConfig } from "astro/config";

export default defineConfig({
  site: "https://example.invalid",
  output: "static",
  trailingSlash: "always",
  build: {
    format: "directory",
    inlineStylesheets: "auto",
  },
  security: {
    checkOrigin: true,
  },
});
