/**
 * Define deterministic unit-test discovery and enforced branch coverage.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - no top-level symbols
 * @@SYMBOL_INDEX_END
 */

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/unit/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "reports/coverage",
      include: ["src/lib/**/*.ts"],
      exclude: ["src/lib/search-client.ts"],
      thresholds: {
        lines: 90,
        functions: 90,
        statements: 90,
        branches: 85,
      },
    },
  },
});
