/**
 * Verify keyboard access, responsive reflow, versioned search, and axe findings.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable WCAG_TAGS: line 13
 * @@SYMBOL_INDEX_END
 */

import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

const WCAG_TAGS = ["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"];

test("homepage has no automatically detectable WCAG A/AA violations", async ({ page }) => {
  await page.goto("/");
  const results = await new AxeBuilder({ page }).withTags(WCAG_TAGS).analyze();
  expect(results.violations).toEqual([]);
});

test("keyboard users can bypass navigation", async ({ page }) => {
  await page.goto("/");
  await page.keyboard.press("Tab");
  const skipLink = page.getByRole("link", { name: "Skip to main content" });
  await expect(skipLink).toBeFocused();
  await skipLink.press("Enter");
  await expect(page.locator("#main-content")).toBeFocused();
});

test("version filter disambiguates a reused diagnostic identifier", async ({ page }) => {
  await page.goto("/search/");
  await page.getByLabel("Version").selectOption("2.0");
  await page.getByLabel("Search documentation").fill("E-104");
  await expect(page.getByText("1 ranked result.")).toBeVisible();
  await expect(
    page.getByRole("link", { name: "Resolve diagnostic E-104" }).first(),
  ).toHaveAttribute("href", "/docs/apex-control-hub/2.0/error-e-104/");
  await expect(
    page.getByRole("region", { name: "Ranked results" }).getByText(/expired or is not yet valid/u),
  ).toBeVisible();
});

test("unknown questions cause explicit abstention", async ({ page }) => {
  await page.goto("/search/");
  await page.getByLabel("Search documentation").fill("lunar rover launch sequence");
  await expect(page.getByText(/Answer unavailable: No sufficiently relevant/u)).toBeVisible();
});

test("topic page exposes version, warning fields, and provenance", async ({ page }) => {
  await page.goto("/docs/apex-control-hub/2.0/error-e-104/");
  await expect(page.getByText("Apex Control Hub 2.0").first()).toBeVisible();
  await expect(page.getByText("Condition", { exact: true })).toBeVisible();
  await expect(page.getByText("Consequence", { exact: true })).toBeVisible();
  await expect(page.getByText("Avoidance", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Source evidence" })).toBeVisible();
});

test("mobile layout does not introduce viewport-wide horizontal scrolling", async ({ page }) => {
  await page.goto("/search/");
  const dimensions = await page.evaluate(() => ({
    viewport: document.documentElement.clientWidth,
    content: document.documentElement.scrollWidth,
  }));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport);
});
