/**
 * Evaluate the lexical index against 50 reviewed queries and write evidence.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - interface Judgment: line 22
 * - interface JudgmentResult: line 28
 * - variable MINIMUM_RECALL_AT_FIVE: line 34
 * - variable MINIMUM_MEAN_RECIPROCAL_RANK: line 35
 * - function loadJudgments: line 38
 * - function main: line 49
 * @@SYMBOL_INDEX_END
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { toSearchDocument } from "../src/lib/content";
import type { SearchFilters } from "../src/lib/contracts";
import { createSearchIndex, search } from "../src/lib/search";
import { loadTopics } from "./load-topics";

interface Judgment {
  readonly query: string;
  readonly expectedIds: readonly string[];
  readonly filters?: SearchFilters;
}

interface JudgmentResult extends Judgment {
  readonly returnedIds: readonly string[];
  readonly reciprocalRank: number;
  readonly passed: boolean;
}

const MINIMUM_RECALL_AT_FIVE = 0.96;
const MINIMUM_MEAN_RECIPROCAL_RANK = 0.9;

/** Parse the versioned query set and reject incomplete cases. */
async function loadJudgments(): Promise<readonly Judgment[]> {
  const parsed: unknown = JSON.parse(
    await readFile(resolve("src/data/search-judgments.json"), "utf8"),
  );
  if (!Array.isArray(parsed) || parsed.length !== 50) {
    throw new Error("search judgment set must contain exactly 50 cases");
  }
  return parsed as readonly Judgment[];
}

/** Evaluate ranking, publish JSON/Markdown evidence, and enforce thresholds. */
async function main(): Promise<void> {
  const topics = await loadTopics();
  const index = createSearchIndex(topics.map(toSearchDocument));
  const judgments = await loadJudgments();
  const results: JudgmentResult[] = judgments.map((judgment) => {
    const returnedIds = search(index, judgment.query, { ...judgment.filters, limit: 5 }).map(
      (result) => result.document.id,
    );
    const rank = returnedIds.findIndex((id) => judgment.expectedIds.includes(id));
    return {
      ...judgment,
      returnedIds,
      reciprocalRank: rank < 0 ? 0 : 1 / (rank + 1),
      passed: rank >= 0,
    };
  });
  const recallAtFive = results.filter((result) => result.passed).length / results.length;
  const meanReciprocalRank =
    results.reduce((sum, result) => sum + result.reciprocalRank, 0) / results.length;
  const report = {
    generatedBy: "pnpm evaluate:search",
    corpusDocuments: topics.length,
    judgmentCount: judgments.length,
    recallAtFive,
    meanReciprocalRank,
    thresholds: {
      recallAtFive: MINIMUM_RECALL_AT_FIVE,
      meanReciprocalRank: MINIMUM_MEAN_RECIPROCAL_RANK,
    },
    results,
  };
  await mkdir(resolve("reports"), { recursive: true });
  await writeFile(
    resolve("reports/search-evaluation.json"),
    `${JSON.stringify(report, null, 2)}\n`,
  );
  const failures = results.filter((result) => !result.passed);
  const markdown =
    `# Search evaluation\n\n` +
    `- Corpus: ${topics.length} versioned topics\n` +
    `- Judgment set: ${judgments.length} reviewed queries\n` +
    `- Recall@5: ${(recallAtFive * 100).toFixed(2)}% (gate ${(MINIMUM_RECALL_AT_FIVE * 100).toFixed(0)}%)\n` +
    `- Mean reciprocal rank: ${meanReciprocalRank.toFixed(3)} (gate ${MINIMUM_MEAN_RECIPROCAL_RANK.toFixed(2)})\n` +
    `- Failed judgments: ${failures.length}\n\n` +
    `The evaluator uses exact product/version filters, exact-identifier boosts, a bounded reviewed\n` +
    `synonym map, and deterministic tie-breaking. Metrics describe only this synthetic corpus and\n` +
    `judgment set.\n`;
  await writeFile(resolve("docs/search-evaluation.md"), markdown);
  console.log(markdown.trim());
  if (recallAtFive < MINIMUM_RECALL_AT_FIVE || meanReciprocalRank < MINIMUM_MEAN_RECIPROCAL_RANK) {
    throw new Error("search relevance gate failed");
  }
}

await main();
