/**
 * Load and minimally validate JSON topics for tools that run outside Astro.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable TOPIC_DIRECTORY: line 16
 * - function isTopicDocument: line 19
 * - function loadTopics: line 34
 * @@SYMBOL_INDEX_END
 */

import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { TopicDocument } from "../src/lib/contracts";

const TOPIC_DIRECTORY = resolve("src/content/topics");

/** Narrow parsed JSON to the fields every offline validation tool requires. */
function isTopicDocument(value: unknown): value is TopicDocument {
  if (typeof value !== "object" || value === null) {
    return false;
  }
  const candidate = value as Partial<TopicDocument>;
  return (
    typeof candidate.id === "string" &&
    typeof candidate.topicSlug === "string" &&
    typeof candidate.productId === "string" &&
    typeof candidate.version === "string" &&
    Array.isArray(candidate.sections)
  );
}

/** Load topics in stable filename order and reject malformed tool input. */
export async function loadTopics(): Promise<readonly TopicDocument[]> {
  const filenames = (await readdir(TOPIC_DIRECTORY))
    .filter((filename) => filename.endsWith(".json"))
    .sort();
  const topics: TopicDocument[] = [];
  for (const filename of filenames) {
    const parsed: unknown = JSON.parse(await readFile(resolve(TOPIC_DIRECTORY, filename), "utf8"));
    if (!isTopicDocument(parsed)) {
      throw new Error(`invalid topic fixture: ${filename}`);
    }
    topics.push(parsed);
  }
  return topics;
}
