/**
 * Generate line-accurate top-level symbol indexes for TypeScript and Astro files.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable ROOT: line 25
 * - variable START: line 26
 * - variable END: line 27
 * - variable SOURCE_EXTENSIONS: line 28
 * - variable SKIPPED_DIRECTORIES: line 29
 * - interface ParsedSource: line 38
 * - function parseSource: line 44
 * - function symbolLabel: line 70
 * - function symbolRows: line 95
 * - function transform: line 109
 * - function sourceFiles: line 130
 * - function main: line 148
 * @@SYMBOL_INDEX_END
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import { extname, relative, resolve } from "node:path";
import ts from "typescript";

const ROOT = resolve(import.meta.dirname, "..");
const START = "@@SYMBOL_INDEX_START";
const END = "@@SYMBOL_INDEX_END";
const SOURCE_EXTENSIONS = new Set([".ts", ".mjs", ".astro"]);
const SKIPPED_DIRECTORIES = new Set([
  ".astro",
  ".git",
  "coverage",
  "dist",
  "node_modules",
  "reports",
]);

interface ParsedSource {
  readonly source: ts.SourceFile;
  readonly lineOffset: number;
}

/** Extract the TypeScript frontmatter from Astro while preserving source line offsets. */
function parseSource(path: string, text: string): ParsedSource {
  if (path.endsWith(".astro")) {
    const end = text.indexOf("\n---", 4);
    if (!text.startsWith("---\n") || end < 0) {
      throw new Error(`Astro file requires frontmatter: ${relative(ROOT, path)}`);
    }
    const frontmatter = text.slice(4, end);
    return {
      source: ts.createSourceFile(
        path,
        frontmatter,
        ts.ScriptTarget.Latest,
        true,
        ts.ScriptKind.TS,
      ),
      lineOffset: 1,
    };
  }
  const scriptKind = path.endsWith(".mjs") ? ts.ScriptKind.JS : ts.ScriptKind.TS;
  return {
    source: ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true, scriptKind),
    lineOffset: 0,
  };
}

/** Return a readable top-level symbol label or omit imports/anonymous exports. */
function symbolLabel(statement: ts.Statement): readonly string[] {
  if (ts.isFunctionDeclaration(statement) && statement.name !== undefined) {
    return [`function ${statement.name.text}`];
  }
  if (ts.isClassDeclaration(statement) && statement.name !== undefined) {
    return [`class ${statement.name.text}`];
  }
  if (ts.isInterfaceDeclaration(statement)) {
    return [`interface ${statement.name.text}`];
  }
  if (ts.isTypeAliasDeclaration(statement)) {
    return [`type ${statement.name.text}`];
  }
  if (ts.isEnumDeclaration(statement)) {
    return [`enum ${statement.name.text}`];
  }
  if (ts.isVariableStatement(statement)) {
    return statement.declarationList.declarations.flatMap((declaration) =>
      ts.isIdentifier(declaration.name) ? [`variable ${declaration.name.text}`] : [],
    );
  }
  return [];
}

/** Build generated rows with one-based positions in the original repository file. */
function symbolRows(path: string, text: string): readonly string[] {
  const { source, lineOffset } = parseSource(path, text);
  return source.statements.flatMap((statement) => {
    const labels = symbolLabel(statement);
    if (labels.length === 0) {
      return [];
    }
    const line =
      source.getLineAndCharacterOfPosition(statement.getStart(source)).line + 1 + lineOffset;
    return labels.map((label) => ` * - ${label}: line ${line}`);
  });
}

/** Replace one generated block; repeated calls converge as the block changes height. */
function transform(path: string, original: string): string {
  let text = original;
  for (let pass = 0; pass < 5; pass += 1) {
    const lines = text.split("\n");
    const start = lines.findIndex((line) => line.includes(START));
    const end = lines.findIndex((line) => line.includes(END));
    if (start < 0 || end <= start) {
      throw new Error(`missing or reversed symbol-index markers: ${relative(ROOT, path)}`);
    }
    const rows = symbolRows(path, text);
    const replacement = rows.length === 0 ? [" * - no top-level symbols"] : rows;
    const updated = [...lines.slice(0, start + 1), ...replacement, ...lines.slice(end)].join("\n");
    if (updated === text) {
      return text;
    }
    text = updated;
  }
  throw new Error(`symbol index did not converge: ${relative(ROOT, path)}`);
}

/** Discover authored code recursively while excluding generated and dependency trees. */
async function sourceFiles(directory: string): Promise<readonly string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths = await Promise.all(
    entries.flatMap((entry) => {
      if (entry.isDirectory() && SKIPPED_DIRECTORIES.has(entry.name)) {
        return [];
      }
      const path = resolve(directory, entry.name);
      if (entry.isDirectory()) {
        return [sourceFiles(path)];
      }
      return SOURCE_EXTENSIONS.has(extname(entry.name)) ? [Promise.resolve([path])] : [];
    }),
  );
  return paths.flat().sort();
}

/** Update files or fail check mode when any generated index is stale. */
async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const stale: string[] = [];
  for (const path of await sourceFiles(ROOT)) {
    const original = await readFile(path, "utf8");
    const updated = transform(path, original);
    if (updated !== original) {
      stale.push(relative(ROOT, path));
      if (!check) {
        await writeFile(path, updated);
      }
    }
  }
  if (stale.length > 0 && check) {
    throw new Error(`stale symbol indexes:\n${stale.join("\n")}`);
  }
  console.log(
    check ? "All symbol indexes are current." : `Updated ${stale.length} symbol indexes.`,
  );
}

await main();
