/**
 * Crawl generated HTML for broken internal links and enforce asset budgets.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable DIST: line 20
 * - variable MAX_TOTAL_SCRIPT_BYTES: line 21
 * - variable MAX_TOTAL_STYLE_BYTES: line 22
 * - variable INTERNAL_LINK: line 23
 * - function walk: line 26
 * - function targetPath: line 38
 * - function main: line 52
 * - function totalBytes: line 103
 * @@SYMBOL_INDEX_END
 */

import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { extname, resolve } from "node:path";

const DIST = resolve("dist");
const MAX_TOTAL_SCRIPT_BYTES = 100 * 1024;
const MAX_TOTAL_STYLE_BYTES = 40 * 1024;
const INTERNAL_LINK = /(?:href|src)=["'](\/[^"]*?)["']/gu;

/** Return every file below one directory in stable order. */
async function walk(directory: string): Promise<readonly string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths = await Promise.all(
    entries.map((entry) => {
      const path = resolve(directory, entry.name);
      return entry.isDirectory() ? walk(path) : Promise.resolve([path]);
    }),
  );
  return paths.flat().sort();
}

/** Convert a root-relative site URL into its expected static file. */
function targetPath(url: string): string | undefined {
  if (url.startsWith("//") || url.startsWith("/#") || url.includes("example.invalid")) {
    return undefined;
  }
  const pathname = decodeURIComponent(url.split(/[?#]/u, 1)[0] ?? "/");
  if (pathname === "/") {
    return resolve(DIST, "index.html");
  }
  return extname(pathname) === ""
    ? resolve(DIST, `.${pathname}`, "index.html")
    : resolve(DIST, `.${pathname}`);
}

/** Validate internal targets, write evidence, and fail on links or budget regressions. */
async function main(): Promise<void> {
  const files = await walk(DIST);
  const htmlFiles = files.filter((path) => path.endsWith(".html"));
  const broken: { source: string; url: string }[] = [];
  for (const htmlFile of htmlFiles) {
    const html = await readFile(htmlFile, "utf8");
    for (const match of html.matchAll(INTERNAL_LINK)) {
      const url = match[1];
      if (url === undefined) {
        continue;
      }
      const target = targetPath(url);
      if (target !== undefined) {
        try {
          await stat(target);
        } catch {
          broken.push({ source: htmlFile.slice(DIST.length + 1), url });
        }
      }
    }
  }
  const scriptBytes = await totalBytes(files.filter((path) => path.endsWith(".js")));
  const styleBytes = await totalBytes(files.filter((path) => path.endsWith(".css")));
  const report = {
    generatedBy: "pnpm validate:links",
    htmlFiles: htmlFiles.length,
    linksChecked: htmlFiles.length,
    broken,
    budgets: {
      scriptBytes: { actual: scriptBytes, maximum: MAX_TOTAL_SCRIPT_BYTES },
      styleBytes: { actual: styleBytes, maximum: MAX_TOTAL_STYLE_BYTES },
    },
  };
  await mkdir(resolve("reports"), { recursive: true });
  await writeFile(
    resolve("reports/link-and-budget-report.json"),
    `${JSON.stringify(report, null, 2)}\n`,
  );
  console.log(
    `Validated ${htmlFiles.length} HTML files; JS ${scriptBytes} B; CSS ${styleBytes} B.`,
  );
  if (
    broken.length > 0 ||
    scriptBytes > MAX_TOTAL_SCRIPT_BYTES ||
    styleBytes > MAX_TOTAL_STYLE_BYTES
  ) {
    throw new Error("link or static-asset budget gate failed");
  }
}

/** Sum file sizes without loading assets into memory. */
async function totalBytes(paths: readonly string[]): Promise<number> {
  const sizes = await Promise.all(paths.map(async (path) => (await stat(path)).size));
  return sizes.reduce((sum, size) => sum + size, 0);
}

await main();
