/**
 * Validate every product topic at build time before a route can be emitted.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable identifier: line 18
 * - variable warning: line 19
 * - variable section: line 25
 * - variable topics: line 34
 * - variable collections: line 59
 * @@SYMBOL_INDEX_END
 */

import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";

const identifier = z.string().regex(/^[A-Z0-9][A-Z0-9._-]{1,31}$/);
const warning = z.object({
  level: z.enum(["notice", "caution", "warning", "danger"]),
  condition: z.string().min(1),
  consequence: z.string().min(1),
  avoidance: z.string().min(1),
});
const section = z.object({
  id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  title: z.string().min(1),
  paragraphs: z.array(z.string().min(1)).min(1),
  steps: z.array(z.string().min(1)).min(1).optional(),
  code: z.string().min(1).optional(),
  warning: warning.optional(),
});

const topics = defineCollection({
  loader: glob({ pattern: "**/*.json", base: "./src/content/topics" }),
  schema: z.object({
    id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    topicSlug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    title: z.string().min(3).max(90),
    summary: z.string().min(20).max(240),
    productId: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    productName: z.string().min(3),
    version: z.string().regex(/^\d+\.\d+$/),
    lifecycle: z.enum(["current", "maintained", "retired"]),
    contentType: z.enum(["concept", "task", "reference", "troubleshooting"]),
    identifiers: z.array(identifier).max(12),
    synonyms: z.array(z.string().min(2)).max(12),
    updated: z.iso.date(),
    visibility: z.literal("public"),
    provenance: z.object({
      sourceId: z.string().min(3),
      pages: z.array(z.number().int().positive()).min(1),
      checksum: z.string().regex(/^[a-f0-9]{64}$/),
    }),
    sections: z.array(section).min(1),
  }),
});

export const collections = { topics };
