/**
 * Verify stable URLs and searchable text derived from canonical topic sections.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable TOPIC: line 14
 * @@SYMBOL_INDEX_END
 */

import { describe, expect, it } from "vitest";
import type { TopicDocument } from "../../src/lib/contracts";
import { toSearchDocument, topicText, topicUrl } from "../../src/lib/content";

const TOPIC: TopicDocument = {
  id: "sample",
  topicSlug: "safe-start",
  title: "Safe start",
  summary: "Start a synthetic device with explicit checks.",
  productId: "sample-product",
  productName: "Sample Product",
  version: "1.0",
  lifecycle: "current",
  contentType: "task",
  identifiers: ["SAFE-1"],
  synonyms: ["boot"],
  updated: "2026-09-16",
  visibility: "public",
  provenance: { sourceId: "source", pages: [1], checksum: "a".repeat(64) },
  sections: [
    {
      id: "start",
      title: "Start",
      paragraphs: ["Check the indicator."],
      steps: ["Apply power."],
      code: "status --json",
      warning: {
        level: "caution",
        condition: "A guard is open.",
        consequence: "Motion can be exposed.",
        avoidance: "Close and verify the guard.",
      },
    },
  ],
};

describe("topic adapters", () => {
  it("builds a version-qualified route", () => {
    expect(topicUrl(TOPIC)).toBe("/docs/sample-product/1.0/safe-start/");
  });

  it("includes procedures, code, and warning fields in plain search text", () => {
    const text = topicText(TOPIC);
    expect(text).toContain("Apply power.");
    expect(text).toContain("status --json");
    expect(text).toContain("Close and verify the guard.");
  });

  it("maps public search fields without leaking provenance", () => {
    const searchDocument = toSearchDocument(TOPIC);
    expect(searchDocument.url).toBe(topicUrl(TOPIC));
    expect(searchDocument).not.toHaveProperty("provenance");
  });
});
