/**
 * Verify reviewed local redirect mappings and reject unknown external targets.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - no top-level symbols
 * @@SYMBOL_INDEX_END
 */

import { describe, expect, it } from "vitest";
import { LEGACY_REDIRECTS, resolveLegacyRedirect } from "../../src/lib/redirects";

describe("legacy redirects", () => {
  it("returns a canonical internal versioned route", () => {
    expect(resolveLegacyRedirect("/manuals/apex/latest/e104")).toBe(
      "/docs/apex-control-hub/2.0/error-e-104/",
    );
  });

  it("does not guess an unknown path", () => {
    expect(resolveLegacyRedirect("/manuals/unknown")).toBeUndefined();
  });

  it("contains only absolute repository-local targets", () => {
    expect(Object.values(LEGACY_REDIRECTS).every((target) => /^\/(?!\/)/u.test(target))).toBe(true);
  });
});
