/**
 * Enforce neutrality, documentation, code headers, content integrity, and CI policy.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable ROOT: line 22
 * - variable CODE_EXTENSIONS: line 23
 * - variable EXCLUDED_DIRECTORIES: line 24
 * - variable REQUIRED_DOCUMENTS: line 32
 * - variable FORBIDDEN_REFERENCE: line 46
 * - function walk: line 49
 * @@SYMBOL_INDEX_END
 */

import { readFile, readdir } from "node:fs/promises";
import { extname, relative, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import redirects from "../../public/redirects.json";
import { LEGACY_REDIRECTS } from "../../src/lib/redirects";
import { loadTopics } from "../../tools/load-topics";

const ROOT = resolve(import.meta.dirname, "../..");
const CODE_EXTENSIONS = new Set([".ts", ".mjs", ".astro"]);
const EXCLUDED_DIRECTORIES = new Set([
  ".astro",
  ".git",
  "coverage",
  "dist",
  "node_modules",
  "reports",
]);
const REQUIRED_DOCUMENTS = [
  "README.md",
  "CONTRIBUTING.md",
  "SECURITY.md",
  "CHANGELOG.md",
  "docs/architecture.md",
  "docs/accessibility.md",
  "docs/content-model.md",
  "docs/file-reference.md",
  "docs/operations.md",
  "docs/search-evaluation.md",
  "docs/security-model.md",
  "docs/testing-and-validation.md",
];
const FORBIDDEN_REFERENCE = ["opto", "22"].join(" ");

/** Walk authored files while excluding dependencies and generated evidence. */
async function walk(directory: string): Promise<readonly string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths = await Promise.all(
    entries.flatMap((entry) => {
      if (entry.isDirectory() && EXCLUDED_DIRECTORIES.has(entry.name)) {
        return [];
      }
      const path = resolve(directory, entry.name);
      return entry.isDirectory() ? [walk(path)] : [Promise.resolve([path])];
    }),
  );
  return paths.flat();
}

describe("repository policy", () => {
  it("contains no target-company references", async () => {
    const textFiles = (await walk(ROOT)).filter((path) =>
      [".ts", ".mjs", ".astro", ".css", ".md", ".json", ".yml", ".yaml"].includes(extname(path)),
    );
    for (const path of textFiles) {
      const text = await readFile(path, "utf8");
      expect(text.toLocaleLowerCase("en-US"), relative(ROOT, path)).not.toContain(
        FORBIDDEN_REFERENCE,
      );
    }
  });

  it("keeps generated line indexes in every code file", async () => {
    const codeFiles = (await walk(ROOT)).filter((path) => CODE_EXTENSIONS.has(extname(path)));
    expect(codeFiles.length).toBeGreaterThan(10);
    for (const path of codeFiles) {
      const text = await readFile(path, "utf8");
      expect(text, relative(ROOT, path)).toContain("@@SYMBOL_INDEX_START");
      expect(text, relative(ROOT, path)).toContain("@@SYMBOL_INDEX_END");
    }
  });

  it("ships the complete documentation set", async () => {
    const authored = new Set(
      (await walk(ROOT)).map((path) => relative(ROOT, path).replaceAll("\\", "/")),
    );
    for (const required of REQUIRED_DOCUMENTS) {
      expect(authored.has(required), required).toBe(true);
    }
  });

  it("pins every third-party action to a full commit SHA", async () => {
    const workflow = await readFile(resolve(ROOT, ".github/workflows/ci.yml"), "utf8");
    const uses = [...workflow.matchAll(/^\s*uses:\s*([^\s#]+)/gmu)].map((match) => match[1] ?? "");
    expect(uses.length).toBeGreaterThan(0);
    expect(uses.every((value) => /@[a-f0-9]{40}$/u.test(value))).toBe(true);
    expect(workflow).toContain("permissions:\n  contents: read");
  });

  it("keeps topic IDs and canonical routes unique with complete warnings", async () => {
    const topics = await loadTopics();
    expect(new Set(topics.map((topic) => topic.id)).size).toBe(topics.length);
    const routes = topics.map((topic) => `${topic.productId}/${topic.version}/${topic.topicSlug}`);
    expect(new Set(routes).size).toBe(routes.length);
    for (const topic of topics) {
      for (const section of topic.sections) {
        if (section.warning !== undefined) {
          expect(section.warning.condition.length).toBeGreaterThan(0);
          expect(section.warning.consequence.length).toBeGreaterThan(0);
          expect(section.warning.avoidance.length).toBeGreaterThan(0);
        }
      }
    }
  });

  it("keeps the published redirect manifest synchronized", () => {
    expect(redirects).toEqual(LEGACY_REDIRECTS);
  });
});
