/**
 * Verify ranking, filters, exact identifiers, bounds, citations, and abstention.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable DOCUMENTS: line 14
 * @@SYMBOL_INDEX_END
 */

import { describe, expect, it } from "vitest";
import type { SearchDocument } from "../../src/lib/contracts";
import { answerQuestion, createSearchIndex, search, tokenize } from "../../src/lib/search";

const DOCUMENTS: readonly SearchDocument[] = [
  {
    id: "new-error",
    title: "Resolve E-104 certificate failure",
    summary: "Replace an expired TLS certificate after checking the clock.",
    headings: ["Meaning", "Resolution"],
    body: "Certificate validity and NTP time synchronization.",
    identifiers: ["E-104", "TLS-CERT"],
    synonyms: ["https fault"],
    productId: "controller",
    productName: "Controller",
    version: "2.0",
    lifecycle: "current",
    url: "/docs/controller/2.0/e-104/",
  },
  {
    id: "old-error",
    title: "Resolve E-104 network conflict",
    summary: "Locate a duplicate IPv4 address with the ARP table.",
    headings: ["Meaning", "Resolution"],
    body: "Ethernet duplicate address and network isolation.",
    identifiers: ["E-104", "ARP-CONFLICT"],
    synonyms: ["duplicate address"],
    productId: "controller",
    productName: "Controller",
    version: "1.5",
    lifecycle: "maintained",
    url: "/docs/controller/1.5/e-104/",
  },
  {
    id: "calibration",
    title: "Calibrate an analog input",
    summary: "Apply zero and span references to a sensor channel.",
    headings: ["Two-point calibration"],
    body: "Inject 4 mA and 20 mA reference currents.",
    identifiers: ["AI-420"],
    synonyms: ["sensor scaling"],
    productId: "gateway",
    productName: "Gateway",
    version: "3.2",
    lifecycle: "current",
    url: "/docs/gateway/3.2/calibration/",
  },
];

describe("tokenize", () => {
  it("normalizes Unicode and preserves compound identifiers", () => {
    expect(tokenize("  E-104 TLS_CERT café  ")).toEqual(["e-104", "tls_cert", "café"]);
  });
});

describe("search", () => {
  const index = createSearchIndex(DOCUMENTS);

  it("boosts an exact identifier", () => {
    const results = search(index, "AI-420");
    expect(results[0]?.document.id).toBe("calibration");
    expect(results[0]?.score).toBeGreaterThan(20);
  });

  it("uses filters to disambiguate a reused error code", () => {
    expect(search(index, "E-104", { version: "2.0" })[0]?.document.id).toBe("new-error");
    expect(search(index, "E-104", { version: "1.5" })[0]?.document.id).toBe("old-error");
  });

  it("expands reviewed synonyms without returning other products", () => {
    const results = search(index, "calibration sensor", { productId: "gateway" });
    expect(results.map((result) => result.document.id)).toEqual(["calibration"]);
  });

  it("returns no result for empty and unmatched bounded input", () => {
    expect(search(index, "")).toEqual([]);
    expect(search(index, "unicorn lunar unrelated")).toEqual([]);
  });

  it("clamps the requested result limit", () => {
    expect(search(index, "resolution", { limit: 1 })).toHaveLength(1);
    expect(search(index, "resolution", { limit: -4 })).toHaveLength(1);
  });
});

describe("answerQuestion", () => {
  const index = createSearchIndex(DOCUMENTS);

  it("returns a cited, version-matched extract", () => {
    const answer = answerQuestion(index, "E-104 certificate", { version: "2.0" });
    expect(answer.status).toBe("answered");
    if (answer.status === "answered") {
      expect(answer.text).toContain("expired TLS certificate");
      expect(answer.citations[0]?.version).toBe("2.0");
    }
  });

  it("abstains when evidence is absent", () => {
    expect(answerQuestion(index, "launch sequence for a lunar rover")).toEqual({
      status: "abstained",
      reason: "No sufficiently relevant, version-matched source was found.",
      citations: [],
    });
  });

  it("handles an empty corpus", () => {
    expect(answerQuestion(createSearchIndex([]), "E-104").status).toBe("abstained");
  });
});
