/**
 * Describe the synthetic product catalog and supported documentation versions.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable PRODUCTS: line 16
 * - variable DEFAULT_PRODUCT_ID: line 49
 * - variable DEFAULT_VERSION: line 50
 * - function requireProduct: line 53
 * - function requireVersion: line 62
 * @@SYMBOL_INDEX_END
 */

import type { Product } from "../lib/contracts";

export const PRODUCTS = [
  {
    id: "apex-control-hub",
    name: "Apex Control Hub",
    description: "A synthetic edge controller for deterministic automation examples.",
    versions: [
      { version: "2.0", lifecycle: "current", released: "2026-03-12" },
      { version: "1.5", lifecycle: "maintained", released: "2025-04-08" },
      {
        version: "1.0",
        lifecycle: "retired",
        released: "2023-09-19",
        endOfSupport: "2026-06-30",
      },
    ],
  },
  {
    id: "northstar-io-gateway",
    name: "Northstar I/O Gateway",
    description: "A synthetic remote I/O gateway used for protocol and calibration guidance.",
    versions: [
      { version: "3.2", lifecycle: "current", released: "2026-05-21" },
      { version: "3.0", lifecycle: "maintained", released: "2025-06-10" },
      {
        version: "2.4",
        lifecycle: "retired",
        released: "2023-02-16",
        endOfSupport: "2026-02-28",
      },
    ],
  },
] as const satisfies readonly Product[];

export const DEFAULT_PRODUCT_ID = PRODUCTS[0].id;
export const DEFAULT_VERSION = PRODUCTS[0].versions[0].version;

/** Return one product or fail during the build rather than emitting a broken route. */
export function requireProduct(productId: string): Product {
  const product = PRODUCTS.find((candidate) => candidate.id === productId);
  if (product === undefined) {
    throw new Error(`unknown product: ${productId}`);
  }
  return product;
}

/** Return one known version or fail during the build. */
export function requireVersion(product: Product, version: string) {
  const selected = product.versions.find((candidate) => candidate.version === version);
  if (selected === undefined) {
    throw new Error(`unknown version ${version} for ${product.id}`);
  }
  return selected;
}
