/**
 * Keep query expansion explicit, reviewable, bounded, and domain-neutral.
 *
 * Symbol index (generated by tools/update-symbol-index.ts):
 * @@SYMBOL_INDEX_START
 * - variable SYNONYMS: line 10
 * @@SYMBOL_INDEX_END
 */

export const SYNONYMS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  auth: ["authentication", "credential", "token"],
  calibration: ["calibrate", "scaling", "span", "offset"],
  error: ["fault", "alarm", "diagnostic"],
  ethernet: ["network", "tcp", "ip"],
  firmware: ["update", "upgrade", "release"],
  input: ["channel", "signal", "sensor"],
  modbus: ["register", "tcp", "mapping"],
  password: ["credential", "secret", "authentication"],
  retired: ["deprecated", "unsupported", "end", "support"],
  tls: ["certificate", "https", "encryption"],
});
